#set Zsh as your default Tmux shell
set-option -g default-shell /bin/zsh


# Tmux should be pretty, we need 256 color for that
set -g default-terminal "screen-256color"

unbind C-b
set -g prefix `
bind ` send-prefix

# Quick ways to kill single windows and the whole server
bind-key '/' confirm-before 'kill-window'
bind-key '\' confirm-before 'kill-server'

# Slightly more intuitive way to split windows
bind-key '_' split-window -v
bind-key '|' split-window -h

# Vim-like pane resizing
bind-key -r '+' resize-pane -U 5
bind-key -r '-' resize-pane -D 5
bind-key -r '<' resize-pane -L 5
bind-key -r '>' resize-pane -R 5

# Vim-like pane switching
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# correct reactiveness for esc key in vim
set -s escape-time 0

bind-key r source-file ~/.tmux.conf \; display 'Config reloaded!'

